export const UPDATE_THEME = 'UPDATE_THEME';

export const LOAD_POPULAR_REFRESH = 'LOAD_POPULAR_REFRESH';
export const LOAD_POPULAR_SUCCESS = 'LOAD_POPULAR_SUCCESS';
export const LOAD_POPULAR_ERROR = 'LOAD_POPULAR_ERROR';