export const UPDATE_THEME = 'UPDATE_THEME';

export const POPULAR_REFRESH = 'POPULAR_REFRESH';
export const POPULAR_REFRESH_SUCCESS = 'POPULAR_REFRESH_SUCCESS';
export const POPULAR_REFRESH_ERROR = 'POPULAR_REFRESH_ERROR';

export const POPULAR_LOAD_MORE = 'POPULAR_LOAD_MORE';
export const POPULAR_LOAD_MORE_SUCCESS = 'POPULAR_LOAD_MORE_SUCCESS';